# sh train_incremental_net_scripts/train_incremental_net_noControl_render_DynamicGaussian.sh
sh train_incremental_net_scripts/train_incremental_net_noControl_render_GoPro.sh
# sh train_incremental_net_scripts/train_incremental_net_noControl_render_NVFi.sh
sh train_incremental_net_scripts/train_incremental_net_noControl_render_ParticleNerf.sh